# Generated by Django 3.2.9 on 2021-12-04 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprolog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
