# Generated by Django 3.2.9 on 2021-12-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprolog', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_user_image.jpeg', null=True, upload_to='images/profile_image'),
        ),
    ]
