# Generated by Django 3.2.9 on 2021-11-07 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cms',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('entry', models.TextField(blank=True, null=True)),
                ('stoploss', models.TextField(blank=True, null=True)),
                ('tptarget', models.IntegerField(blank=True, default=0, null=True)),
                ('tpachieved', models.IntegerField(blank=True, default=0, null=True)),
                ('profit', models.IntegerField(blank=True, default=0, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
