# Generated by Django 3.2.9 on 2021-11-27 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cms',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('entry', models.TextField(blank=True, null=True)),
                ('stoploss', models.TextField(blank=True, null=True)),
                ('tp_target', models.IntegerField(blank=True, default=0, null=True)),
                ('tp_achieved', models.IntegerField(blank=True, default=0, null=True)),
                ('profit', models.IntegerField(blank=True, default=0, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courses', models.TextField(blank=True, null=True)),
                ('course_link', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(default='monthly plan', on_delete=django.db.models.deletion.CASCADE, to='cms.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.cms')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.TextField(blank=True, null=True)),
                ('product_link', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ManyToManyField(blank=True, to='cms.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='cms',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cms.Tag'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('post', models.TextField()),
                ('featured_stories', models.BooleanField(default=False)),
                ('latest_news', models.BooleanField(default=False)),
                ('latest_articles', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('premium', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
