# Generated by Django 3.2.9 on 2021-12-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_on',
            field=models.DateTimeField(default=True),
        ),
    ]
