# Generated by Django 3.2.9 on 2021-11-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
    ]
