# Generated by Django 3.2.9 on 2021-12-16 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 0, 21, 19, 985522, tzinfo=utc)),
        ),
    ]
