# Generated by Django 3.2.9 on 2021-11-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20211108_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cms',
            old_name='tpachieved',
            new_name='tp_achieved',
        ),
        migrations.RenameField(
            model_name='cms',
            old_name='tptarget',
            new_name='tp_target',
        ),
    ]
