# Generated by Django 3.2.9 on 2021-12-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
