# Generated by Django 3.2.9 on 2021-11-28 21:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
