# Generated by Django 3.2.9 on 2021-11-09 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20211109_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[{'Buy', 'BUY'}, {'SELL', 'Sell'}], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.cms')),
            ],
        ),
    ]
