# Generated by Django 3.2.9 on 2021-11-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20211129_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
