# Generated by Django 3.2.9 on 2021-11-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField(blank=True, null=True)),
                ('course_link', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
            ],
        ),
    ]
