# Generated by Django 3.2.9 on 2021-12-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_blog_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
