# Generated by Django 3.2.9 on 2021-11-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_plan_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='transaction_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
