# Generated by Django 3.2.9 on 2021-11-29 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0006_auto_20211129_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='username',
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprolog.user'),
            preserve_default=False,
        ),
    ]
