# Generated by Django 3.2.9 on 2021-11-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
