# Generated by Django 3.2.9 on 2021-11-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20211129_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='amount_paid',
            field=models.SmallIntegerField(default=0),
        ),
    ]
