# Generated by Django 3.2.9 on 2021-11-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20211109_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='cms',
            name='course_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms',
            name='courses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
