# Generated by Django 3.2.9 on 2021-11-10 03:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20211109_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courses', models.TextField(blank=True, null=True)),
                ('course_link', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cms',
            name='course_link',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='courses',
        ),
    ]
