# Generated by Django 3.2.9 on 2021-12-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20211201_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
