# Generated by Django 3.2.9 on 2021-11-10 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20211109_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('stores', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
