# Generated by Django 3.2.9 on 2021-11-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cms.Tag'),
        ),
    ]
