# Generated by Django 3.2.9 on 2021-11-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_store_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='stores_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
