# Generated by Django 3.2.9 on 2021-11-17 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_adminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('poststitle', models.TextField(blank=True, null=True)),
                ('posts', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
