# Generated by Django 3.2.9 on 2021-11-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='adminlogin',
            name='created_by',
        ),
        migrations.AddField(
            model_name='blog',
            name='postsauthour',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
