# Generated by Django 3.1.8 on 2021-11-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20211117_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
