# Generated by Django 3.1.8 on 2021-11-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_blog_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_featured',
            new_name='featured_stories',
        ),
        migrations.AddField(
            model_name='blog',
            name='latest_articles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='latest_news',
            field=models.BooleanField(default=False),
        ),
    ]
