# Generated by Django 3.1.8 on 2021-11-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20211119_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='postsauthour',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
