# Generated by Django 4.0.4 on 2022-05-21 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_alter_subscriptionhistory_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 5, 21)),
        ),
    ]
