# Generated by Django 3.1.8 on 2021-11-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20211119_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=''),
        ),
    ]
