# Generated by Django 3.2.4 on 2022-10-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0026_auto_20221019_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.blog'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('owner', 'blog')},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
