# Generated by Django 3.2.4 on 2022-10-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_remove_comment_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
