# Generated by Django 3.2.4 on 2022-10-24 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_alter_subscriptionhistory_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('blogview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_count', to='cms.blog')),
            ],
        ),
    ]
