# Generated by Django 3.2.4 on 2022-10-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_viewcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='blogview',
            new_name='blog',
        ),
    ]
