# Generated by Django 3.2.4 on 2022-10-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_rename_blogview_viewcount_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blogview',
        ),
    ]
