# Generated by Django 3.2.4 on 2022-10-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_rename_blog_comment_blogview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogview',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='viewcount',
            old_name='blog',
            new_name='blogview',
        ),
    ]
