# Generated by Django 3.2.4 on 2022-10-25 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20221023_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 10, 24)),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='session',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
