# Generated by Django 3.2.4 on 2022-10-25 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20221024_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='blogview',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 10, 25)),
        ),
    ]
