# Generated by Django 3.2.4 on 2022-10-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_auto_20221028_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='entry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cms',
            name='profit',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cms',
            name='stoploss',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cms',
            name='tp_achieved',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cms',
            name='tp_target',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
