# Generated by Django 3.2.9 on 2022-11-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_auto_20221112_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
