# Generated by Django 3.2.9 on 2022-11-19 14:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0044_alter_subscriptionhistory_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTimePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 19)),
        ),
        migrations.CreateModel(
            name='FirstTimeSubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=11)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('transaction_id', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.date(2022, 11, 19))),
                ('expiry_date', models.DateField(default=None)),
                ('active', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(default='monthly plan', on_delete=django.db.models.deletion.CASCADE, to='cms.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
