# Generated by Django 3.2.9 on 2022-11-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_auto_20221119_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimeplan',
            name='title',
            field=models.CharField(choices=[('montly plan', 'monthly plan'), ('quarterly plan', 'quarterly plan'), ('half a year plan', 'half a year plan')], max_length=90),
        ),
    ]
