# Generated by Django 3.2.9 on 2022-11-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_alter_firsttimeplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttimeplan',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
