# Generated by Django 3.2.9 on 2022-11-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0048_alter_firsttimeplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimeplan',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
