# Generated by Django 3.2.9 on 2022-11-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0049_alter_firsttimeplan_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firsttimeplan',
            old_name='duration',
            new_name='duration_in_days',
        ),
    ]
