# Generated by Django 3.2.9 on 2022-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_rename_duration_firsttimeplan_duration_in_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firsttimeplan',
            old_name='discount',
            new_name='discount_percentage',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='discount',
            new_name='discount_percentage',
        ),
        migrations.AlterField(
            model_name='firsttimeplan',
            name='title',
            field=models.CharField(choices=[('monthly plan', 'monthly plan'), ('quarterly plan', 'quarterly plan'), ('half a year plan', 'half a year plan')], max_length=90),
        ),
    ]
