# Generated by Django 3.2.9 on 2022-11-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_alter_firsttimeplan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimeplan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
