# Generated by Django 3.2.9 on 2022-11-19 16:57

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0053_alter_firsttimeplan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_in_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(choices=[('monthly plan', 'monthly plan'), ('quarterly plan', 'quarterly plan'), ('half a year plan', 'half a year plan')], max_length=90, validators=[cms.models.validate_existing_plan]),
        ),
    ]
