# Generated by Django 3.2.9 on 2022-12-04 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_alter_firsttimeplan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimesubscriptionhistory',
            name='plan',
            field=models.ForeignKey(default='monthly plan', on_delete=django.db.models.deletion.CASCADE, to='cms.firsttimeplan'),
        ),
        migrations.AlterField(
            model_name='firsttimesubscriptionhistory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 4)),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 4)),
        ),
    ]
