# Generated by Django 3.2.9 on 2022-12-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0059_auto_20221211_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimesubscriptionhistory',
            name='plan',
            field=models.ForeignKey(default='weekly plan', on_delete=django.db.models.deletion.CASCADE, to='cms.firsttimeplan'),
        ),
    ]
