# Generated by Django 3.2.9 on 2022-12-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0060_alter_firsttimesubscriptionhistory_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimesubscriptionhistory',
            name='plan',
            field=models.ForeignKey(default='monthly plan', on_delete=django.db.models.deletion.CASCADE, to='cms.firsttimeplan'),
        ),
    ]
