# Generated by Django 3.2.9 on 2022-12-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0061_alter_firsttimesubscriptionhistory_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimeplan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
