# Generated by Django 3.2.9 on 2022-12-12 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0063_auto_20221211_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimeplan',
            name='title',
            field=models.CharField(choices=[('weekly plan', 'weekly plan'), ('monthly plan', 'monthly plan'), ('quarterly plan', 'quarterly plan'), ('half a year plan', 'half a year plan'), ('a year plan', 'a year plan')], max_length=90),
        ),
        migrations.AlterField(
            model_name='firsttimesubscriptionhistory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(choices=[('weekly plan', 'weekly plan'), ('monthly plan', 'monthly plan'), ('quarterly plan', 'quarterly plan'), ('half a year plan', 'half a year plan'), ('a year plan', 'a year plan')], max_length=90),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
    ]
