# Generated by Django 3.2.9 on 2021-12-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprolog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_user_image.jpeg', null=True, upload_to='profile_image/'),
        ),
    ]
